-
  name: 'Coca Cola'
  price: 200
  quantity: 2
-
  name: 'Sprite'
  price: 250
  quantity: 2
-
  name: 'Fanta'
  price: 270
  quantity: 3
-
  name: 'Orange Juice'
  price: 300
  quantity: 1
-
  name: 'Water'
  price: 325
  quantity: 0